project:
  type: website

website:
  title: "DMF Data Science"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - Services.qmd
      - research.qmd
      - contact.qmd
      
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

